### ISSUE TITLE
Linkedin login stopped working again (Invalid authorization code. Pass in the "code" parameter from your callback url)

### ISSUE THREAD

**Issue by gorfreed** [stranoweb/stranoweb-ajax-login#11]
Unfortunately the authorization via LinkedIn has stopped working again. Upon submitting your credentials via the LinkedIn login window,the message "Invalid authorization code. Pass in the "code" parameter from your callback url" is displayed. I wanted to check the callback url on Wordpress, but the field that should display the address in the Stranoweb interface is just empty. I already tried to reinstall but it didnt change. Could you please advise what to do here?

![image](https://user-images.githubusercontent.com/6634117/82696792-043f2380-9c68-11ea-90b9-3cf61e95f8e0.png)

**Comment by stranoweb** [comment]
Hi, it seems you are using an old version of my plugin, which version have you installed?

**Comment by gorfreed** [comment]
I just checked and indeed I was running an out dated version, simply because I was not aware that it requires manual regular updating much like nothing else when it comes to WordPress plugins ... So I went to your website and logged into my account to download the latest version of Stranoweb Premium, updated it common turns out the issue still happens same error message nothing changed, meaning the assumption that the error message points at an outdated version is false. The issue is still present.

**Comment by stranoweb** [comment]
You are right, maybe Linkedin have updated something again.
Will check it out and fix it.
Thanks for letting me know

**Comment by gorfreed** [comment]
That would be great. Do you have an approx. ETA? My clients cannot log in via Linkedin currently and I need to reset their passwords a lot...

**Comment by stranoweb** [comment]
We are currently working on new features we have already planned, i hope we can fix it in the next 3 or 4 days.
Thanks for your patience

**Comment by stranoweb** [comment]
The update that fixes this issue has just been released.
