### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by PatrickGilles** [stranoweb/stranoweb-ajax-login#12]
Hi, 
the login works with administration permission but it does not work with the "group leader" permision. the login indicates a success login but it does not .
Best regards
Patrick

**Comment by stranoweb** [comment]
Hi Patrick, 
Thanks for using my plugin.
Can you be more specific please?
Is that “group leader” a custom role?
Are you using caching plugin and which one?
Thanks

**Comment by PatrickGilles** [comment]
Hi, thank you for your help, it was a caching plugin issue !. (wp fastest cache). Sorry but i’ve got another request... this plugin does not work with internet explorer but you use a redirection to another panel on your site, how do you do that  ! thank you. Have a nice day
Patrick
