### ISSUE TITLE
Is that normal? Plugin is not really working.

### ISSUE THREAD

**Issue by brazogordo** [stranoweb/stranoweb-ajax-login#14]
I am trying to find out, if the plugin interacts with other plugins, but without success until now. 
My problems don't definitively depend on the theme, because I changed it without variation. 
It is 1. impossible to localize the login mask (other masks worked, with localizising po file  and with the overwriting function of the plugin itself), and, 2. if I try to log in with wrong password  or wrong user, all stays stuck, until I recharge the side. 3. Lost password is not working. On the contrary logout and conditional menus are working fine, and login, if I type an existing user with the wright password.  
Has somebody an idea, what the solution could be?
Thanks

**Comment by stranoweb** [comment]
Hi,

Regarding points 2 and 3, are you using a caching plugin? Try to disable nonces on SWAL admin on Advanced tab, it should fix the issues.

Regarding point 1, not sure to understand your question.

Please let me know

**Comment by brazogordo** [comment]
Hallo thank you for this fast and competent answer!

Well, disabling SWAL nonces doesn't seem to play a role. I resume my problems was the login was stuck, after typing wrong password,

The problem seems to be an incompatibility with

1. a redirection snippet, that I did'nt need, because the needed funtionality was in your plugin also.

2. an incompatibility with the plugin "Pro Membership Paid". Unfortunately I haven't found a configuration of PMP (caching or redirection I would guess) to solve this problem.
If you have an idea please let me now, PMP is actually a good plugin, not impossible but difficult to replace, for the goal.


many regards!

**Comment by stranoweb** [comment]
Can you please post the website link? I will give it a check about the url returned by the wrong credentials.
Did you enable register recaptcha without entering the key? That can be a reason

**Comment by brazogordo** [comment]
migruppe.com/adesso

I have activated the plugin "Paid Membership Pro" to provocate the mistake to take place. Please apologise the look, the website is yet in a very primitive status, and the texts are not yet completely translated, because I have canceled the spanish *.po file which was derivated from the *.pot. Thank you for looking for that.

**Comment by stranoweb** [comment]
Actually the issue I think is coming from Paid Membership Pro, when you try to login with wrong credentials it returns an url like this:  https://migruppe.com/adesso/login/?action=failed&username=aaa&redirect_to=https%3A%2F%2Fmigruppe.com%2Fadesso   Instead of the expected json.
I don't know that plugin you are using so I can't help you at the moment, but will try it out and see if I can make my plugin 100% compatible with it

**Comment by brazogordo** [comment]
Hallo! I ask you, if it was possible for you to reproduce the error. I have tried to combine different configurations of both plugins without result. But I have discovered something interesting after trying successfully to reproduce the error. The bare installing and activating both plugin doesn't cause any problem. The problem presented itself again when I generated automatically the pages of PMP. Among them there is also a login. Cancelling manually this page didn't work, of course, the problem is the generated link. I suppose now, it 's not your problem, but a problem of PMP.

**Comment by brazogordo** [comment]
I have found a workaround. I don't know, if you agree, I would consider topic as closed, thogh the solution is not really "elegant".
The solution was: in the settings of PMP go to Advanced and set that we want to cancel all settings togheter with next cancellling of the plugin. Than go to plugins, desactivate and deinstall PMP. Reinstall and activate PMP. Now go to settings pages, and choose to create pages manually. Create pages paciently manually with the given shortcode. Avoid to touch anything, at the login setting of the pages. (Let on Wordpress default). As you see, the problem wasn't in your plugin, but in PMP as I supposed. Many thanks!

**Comment by stranoweb** [comment]
I’m glad you found a way to fix it!
Ok so let’s consider this issue fixed.
Thanks again for using StranoWeb Ajax Login
