### ISSUE TITLE
It was a redirection

### ISSUE THREAD

**Issue by brazogordo** [stranoweb/stranoweb-ajax-login#15]
Sorry for problem number 2 and number 3, I have found a solution. The problem was the redirection after login, a php snippet, I introduced. Problem No. 1, still exists, with the localization, and als the "password forgotten" mask is not showing the translation. But I think, I will overwrite the php itself, 
Many thanks!

**Comment by stranoweb** [comment]
No need to overwrite the php, your changes will get lost on the next update.
In what language would you like to translate?
You should open the original .po file with Poedit, translate in your language and add the language locale to the file name, example sw-ajax-login-it_IT.po and save in /wp-content/languages/plugins/ (just recalling the path without staying in front of my computer so it might be slightly different).
If you are using Premium version those texts are editable from admin.

**Comment by brazogordo** [comment]
I am translating into Spanish. Some original text passages are not in the original po file, for this reason I would suppose to be able to find them in the php. An example: "lost password?" or "back in mind". The text "lost password?" could come from Wordpress itself. It 's actually present there, but of course already translated into Spanish. Even the function "login text (opcional)" ist not working (not overwriting the english text), on the other side "logout text (opcional)", works perfectly.

**Comment by stranoweb** [comment]
That’s weird because those texts are into .po file.
What version have you installed?

**Comment by brazogordo** [comment]
Many thank for your help! 
I am using the last version 1.7.4, but thank to your advise, I solved the problem: I was creating the new language file from the .pot file, and not from the .po file. The .po file does have actually those texts, not the pot. Sorry, but I didn't think of this posibility, because for another plugin it was not a problem to translate the pot. Have you perhaps an idea for m other issue: the incompatibility between Stranoweb and Paid Membership Pro, in both cases last version?

**Comment by stranoweb** [comment]
I mark this issue as solved
