### ISSUE TITLE
Problems with removing the plugin

### ISSUE THREAD

**Issue by Warshander** [stranoweb/stranoweb-ajax-login#18]
Hello. If I deactivate the Ajax Login plugin, I can't install new plugins via the "Plugins -> add new" menu. Also, information about plugins is not displayed in this menu. Plugins are installed manually. Completely removing the Ajax Login plugin doesn't help. To start installing new plugins via dashboard again, you need to activate Ajax Login. What to do?

**Comment by stranoweb** [comment]
The issue has been solved
