### ISSUE TITLE
Google social login

### ISSUE THREAD

**Issue by Ludox9** [stranoweb/stranoweb-ajax-login#2]
Hello,
I am very satisfied to have bought your plugin.
I have a little problem :
I want to validate my app on Google but they tell me to respect the Google sign-in branding guidelines.
Looking, I see that Google imposes new buttons that are not in your plugin.
Could you do this update?
Thank you in advance,
Ludovic

**Comment by stranoweb** [comment]
The plugin has been updated with the new Google Sign In button guideline. Thanks for the feedback
