### ISSUE TITLE
Plugin creating multiple copies of the same page.

### ISSUE THREAD

**Issue by algsupport** [stranoweb/stranoweb-ajax-login#21]
Hi there,
Hope you are doing well. I am writting to inform you of an issue I have with the Ajax Login plugin.
I have been using it sometime now and I have to say it's great. But I have a minor issue.
It is constantly creating new pages like: Forgot Password — SW Ajax Login - Forgot Password Page
It is creating them multiple times. Sometimes even 10 of them exist at any given time.
Please advise how to solve this. The issue occurs with all the plugin's pages not just Forgot Password — SW Ajax Login - Forgot Password Page.

**Comment by stranoweb** [comment]
Hi,
thanks for using our plugin and sorry for the late reply.
Is it happening all the times again? are you using any specific builder like Elementor, WP Bakery or others?
Thanks

**Comment by stranoweb** [comment]
The issue has been fixed with the last update 1.8.4
