### ISSUE TITLE
Social Login is not working if you have WooCommerce installed in your site 

### ISSUE THREAD

**Issue by mfali728** [stranoweb/stranoweb-ajax-login#24]
There is very strange issue i am facing on all my 3 sites.
if you have woocommerce installed in your site then social logins of your plugin is not gonna log you in however it will register your user if you're not already registered on site but it will not log you in, and here comes the most strange part.
it will log you in via social logins only if you go to my accounts page of woocommerce and then click on ajax popup to login with social logins, it will perfectly fine only if you're on my accounts page.

I am working with plugin team to fix this issue, I'll update with solution if we'll found any.

**Comment by stranoweb** [comment]
this is an old post that has been solved.
The problem was due to a server limitation settings.
