### ISSUE TITLE
Reset password link not working on Modal

### ISSUE THREAD

**Issue by Norm6257** [stranoweb/stranoweb-ajax-login#28]
Hi,  I'm posting this here as a duplicate of the WP Support issue just in case you haven't seen it.

https://wordpress.org/support/topic/forgot-password-link-on-modal-not-working/

Recently the “Forgot password” link that is displayed on the popup modal isn’t working. Hovering over the link the url looks to be correct. But clicking on the link produces no action… it’s like the click goes into the bit bucket.

This was configured and worked not too long ago, but I just checked three of my sites and all of them are showing the same behavior (non-functional ‘Forgot password’ link).

Also, I tried it on a test site with Stranoweb being the only plugin active and the issue was there too.

I tested with v1.8.1 and the Forgot Password link worked... I tested with v1.8.5 and the Forgot Password link failed.

You can see an example of one of the sites by going to https://entreTools.com

**Comment by stranoweb** [comment]
Hi Norm,

thanks for reporting, the issue has been fixed with 1.8.8 release.
It happened when user registration was disabled.
