### ISSUE TITLE
Redirect after log-out not working - Stranoweb Ajax Login Version 1.2.1

### ISSUE THREAD

**Issue by denzio** [stranoweb/stranoweb-ajax-login#3]
Hi,

Need your help on Redirect after log-out is not working. It does not redirect to Custom url or Home page. It always go to login page.

Please help.

Thanks,
Dennis

**Comment by stranoweb** [comment]
Hi Denzio,
Thanks for letting us know about the issue, we have fixed and the new update will be released very soon.

**Comment by stranoweb** [comment]
The issue has been solved with the release 1.2.2 already in the WordPress plugins repository.
