### ISSUE TITLE
Conflict with Beaver Builder text editor module

### ISSUE THREAD

**Issue by Norm6257** [stranoweb/stranoweb-ajax-login#30]
Hi,

This is a duplicate issue notice to what I posted in the WP support forum (not sure if issues should be reported here or in WP support).

The WP support issue is here: https://wordpress.org/support/topic/conflict-with-beaverbuilder-editor/

When SWAL is active, the BB text editor tool bar gets changed. Depending on what module is being used, either the editor tool bar buttons are significantly changed, or the disappear entirely.  Here's a screenshot comparing with/without SWAL loaded.

![image](https://user-images.githubusercontent.com/43974318/168886668-b44d45e5-521a-4e19-9079-e85ccb74ddf2.png)

Let me know if there's anything I can do to help troubleshoot.

Thanks, -Norm

**Comment by stranoweb** [comment]
Release 1.9.0 fixes the problem
