### ISSUE TITLE
Incorrect ID of SWAL login page in pages list

### ISSUE THREAD

**Issue by Norm6257** [stranoweb/stranoweb-ajax-login#31]
Hi,

In the SWAL settings I change the login page to a custom page.  However, when viewing the WP pages list it shows the default page as the SWAL login page rather than the custom page.

![image](https://user-images.githubusercontent.com/43974318/188708331-1e9f6d7b-c1e0-4cc5-b879-c89e7dd49ae1.png)

![image](https://user-images.githubusercontent.com/43974318/188708506-f9a6c143-5807-457f-b747-96c07c9ea396.png)

**Comment by stranoweb** [comment]
Hi Norm, thanks for reporting the issue.
We actually confirm the bug and will work to fix it.

Best

**Comment by stranoweb** [comment]
The issue has been fixed with release 1.9.2
