### ISSUE TITLE
Wordfence 2FA incompatibility

### ISSUE THREAD

**Issue by marriesvdh** [stranoweb/stranoweb-ajax-login#32]
As admin, I cannot find a way to login with Wordfence 2FA.

While it would be understandable that the SWAL login form does not provide for the 2FA code to be entered, SWAL completely disables the regular wp-login.php page. So I'm not able to use the default Wordfence 2FA login method, and I'm not aware of an alternative way of logging in with 2FA.

**Comment by marriesvdh** [comment]
A workaround is by adding the following line to the functions.php file:
`remove_action('init','swal_redirect_login_page', 100);`

This enables the wp-login.php page again.

**Comment by stranoweb** [comment]
Hi there,
Thanks for pointing us on this one. Actually SWAL was born to completelly disable and replace thedefault WordPress login and register pages.
As in your case you want to run both worlds so we have added a new advanced option available in the next update to not disable the default login page.

**Comment by marriesvdh** [comment]
Super, thank you!
