### ISSUE TITLE
Rewrite rules flushed during same HTTP request

### ISSUE THREAD

**Issue by Norm6257** [stranoweb/stranoweb-ajax-login#34]
Hi, 

I've been having some issues on the site with content not found. I've been working with Jose over at Freesoul Deactivate Plugins and they have identified an issue with SWAL flushing the rewrite rules on every load.  Here is some information from FDP...

Be careful! It looks like SW AJAX LOGIN updates the rewrite rules during the same HTTP request.
FDP rebuilt again the rewrite rules with all plugins active. You should not have issues due to missing rewrite rules, but you may have more load on your server if SW AJAX LOGIN frequently updates the rewrite rules.
Please, open a thread on the FDP support forum, and give us the information below.

Rewrite Rules updated by the function "flush_rewrite_rules" in the file "wp-content/plugins/sw-ajax-login/admin/sw-ajax-login-admin-settings.php" at line 30 of the plugin SW AJAX LOGIN

The rewrite rules where updated requesting /wp-admin/admin.php?page=eos_dp_by_post_requests

Here an extract of the code:

028      //get the permalink just saved and flush rewrite rules
029      Layers_SwAjaxLogin::prefix_swal_rewrite_rule();
030      flush_rewrite_rules();
031  
032  }
033  

Can you look at this concern and see if there is a way of fixing it? Maybe the rewrite rules shouldn't be flushed.

Thanks,
-Norm

**Comment by stranoweb** [comment]
Hi Norm,

I will look into it and come back soon.
Thanks for the report.
Best

**Comment by stranoweb** [comment]
The issue has been fixed, the update of the Premium version is already available to download.
Free version update will follow soon.
Best
