### ISSUE TITLE
Trigger popup via url param

### ISSUE THREAD

**Issue by Norm6257** [stranoweb/stranoweb-ajax-login#35]
I'm entering this request here just so it doesn't get lost in the shuffle. It's tracking the request to have SWAL modals activated via url param. It's also on the WordPress forum at https://wordpress.org/support/topic/trigger-popup-via-url/

Please implement the ability to activate the SWAL popup via url param. All the modals should be supported including:

- Login (Done. Though it may make sense to change the param from swal=open to swal=login)
- Registration
- Password reset

Thanks,
-Norm

**Comment by stranoweb** [comment]
Thanks for the suggestion, I will add to the todo list.

Best

**Comment by stranoweb** [comment]
Added in the new version 1.9.8 the ability to open popup with the following querystrings:

- swal=login
- swal=register
- swal=lostpassword

I kept the old swal=open for backwards compatibility
