### ISSUE TITLE
Formatting and verbiage of reset password expired key.

### ISSUE THREAD

**Issue by Norm6257** [stranoweb/stranoweb-ajax-login#36]
When someone clicks a reset password link in an email, but that link (key) is expired, there is a very unnoticable notification shown on the password reset page.

Where can I change the text of this notification and format it so that it is very apparent to the user? Multiple users are missing this notification and becoming confused as to why they are always redirected to the reset password page.

![image](https://user-images.githubusercontent.com/43974318/217941986-52df0681-9375-4254-848b-ee606a25124e.png)

**Comment by stranoweb** [comment]
Hi Norm,

You can customize the appearance adding some custom css.
Here are the selector you can use:

#resetPassword .status.show-status.error {
    /* add here your rules */
}

Let me know if it works

**Comment by Norm6257** [comment]
Thanks... I've formatted it using CSS. Probably should be some base default CSS already set up for it so it doesn't show so poorly without it.  This is the CSS that I used:

`
div#resetPassword p.status.show-status.error {
	color: var(--Link);
	font-size: 2rem;
	text-align: center;
	margin-top: 2rem;
}

div#resetPassword p.status.show-status.error::before {
	font-family: 'Font Awesome 5 Free';
	font-weight: 900;
	margin-right: 10px;
	margin-left: 10px;
	content: "\f071";
}

div#resetPassword p.status.show-status.error::after {
	margin-right: 2rem;
	margin-left: 2rem;
	content: "Please request a new link.";
}
`

-Norm
