### ISSUE TITLE
Redirect caused by missing trailing slash in some permalinks

### ISSUE THREAD

**Issue by Norm6257** [stranoweb/stranoweb-ajax-login#39]
Hi,

In the SWAL permalinks settings, some of the default pages don't have a trailing slash (/login, /register, /forgot_password, /account). So when the html of a page is created and SWAL injects the permalinks, those links don't have a trailing slash.  Note that "reset_password" and "logout" do have the trailing slash.

Then, when one of those links is clicked, a redirect (and associated time delay) is added to the request. For example, if **forgot_passoword** is clicked there is a redirect to ".../forgot_passoword/" and an associated delay (2.93 seconds in my screenshot example.)

Example screenshot:

![image](https://github.com/stranoweb/stranoweb-ajax-login/assets/43974318/7f7a0496-7e2d-4a1a-9fef-dc78049e1588)

Can you add the trailing slash to the permalinks?

Thanks,
-Norm

**Comment by stranoweb** [comment]
Hi Norm,

thanks for reporting the issue.

**Comment by Norm6257** [comment]
Any thoughts as to a fix ETA?

**Comment by Norm6257** [comment]
I was just doing some testing and it looks like this issue has been resolved in v2.0.3.  Can you confirm?

**Comment by stranoweb** [comment]
Hi Norn,

Yes it's been fixed.
Thanks for the report.
