### ISSUE TITLE
Error with submenu to logged in user

### ISSUE THREAD

**Issue by therambino** [stranoweb/stranoweb-ajax-login#4]
Hi, 

Thanks for an amazing looking, efficient profile management plugin. 

The submenu on my page appears as bullet points and not a dropdown. Any reason why? I have followed the steps to add the submenu items and mark the menu as SW Ajax Login User Menu.

Please see screenshot below:
![image](https://user-images.githubusercontent.com/52120043/59973263-cd671600-959d-11e9-9956-b29f41dd26f3.png)

Looking forward to purchasing the pro version.

**Comment by stranoweb** [comment]
Hi, thanks for using our plugin.
Can you provide an url where I can see the issue? 
it seems related to the theme you are using, which one is it?
Thanks

**Comment by therambino** [comment]
Hi,
The URL is https://cookingpro.co.za
Theme is kale pro from https://lyrathemes.com/

Thanks.

**Comment by stranoweb** [comment]
I've checked your website and the theme you are using, it adds some extra custom css classes to manage the dropdown menus, these classes are applied to `<li>` `<a>` and `<ul>` elements.

To manage the extra classes, that may vary from theme to theme, we have made a specific section available on the Premium version.

**Comment by therambino** [comment]
Perfect, thanks!
