### ISSUE TITLE
Fatal error conflict with SureCart

### ISSUE THREAD

**Issue by Norm6257** [stranoweb/stranoweb-ajax-login#41]
Hi, 

When using SureCart on a site I'm getting a fatal error when trying to view a SureCart product. An example fatal error is:

`Fatal error: Uncaught TypeError: SureCart\Controllers\Web\BasePageController::disallowPreTitle(): Argument #1 ($title) must be of type string, null given, called in /home2/nerdmans/domains/amapa.club/public_html/wp-includes/class-wp-hook.php on line 324 and defined in /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/app/src/Controllers/Web/BasePageController.php:166 Stack trace: #0 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/class-wp-hook.php(324): SureCart\Controllers\Web\BasePageController->disallowPreTitle() #1 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters() #2 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/general-template.php(1178): apply_filters() #3 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/block-template.php(202): wp_get_document_title() #4 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/class-wp-hook.php(324): _block_template_render_title_tag() #5 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #6 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #7 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/general-template.php(3052): do_action() #8 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/template-canvas.php(17): wp_head() #9 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/app/src/Controllers/Web/ProductPageController.php(51): include('/home2/nerdmans...') #10 [internal function]: SureCart\Controllers\Web\ProductPageController->show() #11 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Helpers/Handler.php(148): call_user_func_array() #12 [internal function]: SureCartCore\Helpers\Handler->execute() #13 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Kernels/HttpKernel.php(177): call_user_func_array() #14 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Kernels/HttpKernel.php(208): SureCartCore\Kernels\HttpKernel->executeHandler() #15 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Middleware/ExecutesMiddlewareTrait.php(40): SureCartCore\Kernels\HttpKernel->SureCartCore\Kernels\{closure}() #16 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Middleware/ExecutesMiddlewareTrait.php(44): SureCartCore\Kernels\HttpKernel->executeMiddleware() #17 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Input/OldInputMiddleware.php(44): SureCartCore\Kernels\HttpKernel->SureCartCore\Middleware\{closure}() #18 [internal function]: SureCartCore\Input\OldInputMiddleware->handle() #19 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Middleware/ExecutesMiddlewareTrait.php(53): call_user_func_array() #20 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Middleware/ExecutesMiddlewareTrait.php(44): SureCartCore\Kernels\HttpKernel->executeMiddleware() #21 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Flash/FlashMiddleware.php(40): SureCartCore\Kernels\HttpKernel->SureCartCore\Middleware\{closure}() #22 [internal function]: SureCartCore\Flash\FlashMiddleware->handle() #23 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Middleware/ExecutesMiddlewareTrait.php(53): call_user_func_array() #24 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Kernels/HttpKernel.php(209): SureCartCore\Kernels\HttpKernel->executeMiddleware() #25 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Kernels/HttpKernel.php(241): SureCartCore\Kernels\HttpKernel->run() #26 /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/core/core/src/Kernels/HttpKernel.php(339): SureCartCore\Kernels\HttpKernel->handle() #27 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/class-wp-hook.php(324): SureCartCore\Kernels\HttpKernel->filterTemplateInclude() #28 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters() #29 /home2/nerdmans/domains/amapa.club/public_html/wp-includes/template-loader.php(104): apply_filters() #30 /home2/nerdmans/domains/amapa.club/public_html/wp-blog-header.php(19): require_once('/home2/nerdmans...') #31 /home2/nerdmans/domains/amapa.club/public_html/index.php(17): require('/home2/nerdmans...') #32 {main} thrown in /home2/nerdmans/domains/amapa.club/public_html/wp-content/plugins/surecart/app/src/Controllers/Web/BasePageController.php on line 166`

I've contacted SureCart support with the error and their reply is "It looks like the "Stranoweb Ajax Login Premium" plugin is using the [pre_get_title](https://developer.wordpress.org/reference/functions/get_the_title/) incorrectly. This filter requires a string be returned and it looks like this plugin is returning null value. Are you able to reach out to them and see if they can fix this on their end?"

Do you agree with this and if so, can you provide a fix?

Thanks,
-Norm

**Comment by stranoweb** [comment]
Hi Norm, 
I will give it a look.
Thanka

**Comment by stranoweb** [comment]
Hi Norm, hope you are well.

I've checked and SWAL isn't using that WordPress functions, neither get_the_title, which you refer in the link you posted.

**Comment by Norm6257** [comment]
Thanks. I'll provide the feedback to SureCart. Meanwhile, they have issued a version that loosens up their type checking and it seems to be working OK with that release.
