### ISSUE TITLE
Non-SWAL plugin details blocked by 'swal_plugin_info'

### ISSUE THREAD

**Issue by Norm6257** [stranoweb/stranoweb-ajax-login#42]
I've been having issues with some Pro plugins not displaying their update information when clicking on their details link in the WP plugins list.  I tracked it down to SWAL being active.  One of the developers, Jack from WP Fusion, looked into it and has responded that SWAL is hijacking the plugin details information.  Here is his response:

_
It's the hook added in class-sw-ajax-login.php:

add_filter('plugins_api', array( $this, 'swal_plugin_info'), 20, 3);

Any plugin that uses the plugins_api filter to add custom plugin updates passes through their filter. If the plugin name in question isn't their plugin, they block the response.

Any plugin that uses EDD for updates (which is most) would be affected. You'll need to contact them and ask them to fix it so that it doesn't block other plugins from displaying update info.
_

Can you get this fixed?

Thanks,
-Norm

**Comment by stranoweb** [comment]
Hi Norm,

i will look into it, thanks for reporting

**Comment by Norm6257** [comment]
I've been testing out SWAL v2.0.5 and this issue appears to be fixed.  Closing.
