### ISSUE TITLE
Lost password e-mail not sending

### ISSUE THREAD

**Issue by therambino** [stranoweb/stranoweb-ajax-login#5]
Hi, 

When the lost password link is selected and the e-mail entered and submitted, I get a confirmation to check my e-mails. However, the e-mail isn't in my inbox or spam folder. 

URL - https://cookingpro.co.za

**Comment by therambino** [comment]
The e-mail came through ultimately, but took around 20mins. Is that expected?

**Comment by stranoweb** [comment]
Our plugin uses WordPress email functions that are tested and working, so any delay or issue could be related to server settings or temporary down.
