### ISSUE TITLE
Blank pages for redirected pages

### ISSUE THREAD

**Issue by Neyiox** [stranoweb/stranoweb-ajax-login#6]
Hello,

I have an issue on all the redirected pages.

www.heartentales.com/login
www.heartentales.com/account/login
www.heartentales.com/account/register
(ect...)

The pages are blank, do you have an idea of what the problem is ?

Thank you 🙏🏻

**Comment by stranoweb** [comment]
Hi Neyiox,

It seems a theme issue, have you tried to switch to one of WordPress default’s theme and see if you get the same problem?

**Comment by Neyiox** [comment]
Yes and it works. But I need it to work with my actual Theme. The website is under X Theme (cornerstone). When I create a new page and add the shortcodes, then it works great. But the links within the shortcodes redirect to the blank pages so it is useless. Is there a way to change the links or stop the redirection of the default wordpress login/register/forgot the password in the files codes ?

Thank you for your time!

**Comment by stranoweb** [comment]
We are about to release the next update that adds the full management of the custom pages, this will avoid any kind of issue with some themes.

**Comment by Neyiox** [comment]
Oh great! I will wait then and continue to use it even with the issue! I'm running the free version of your plugin. I hope that the update you're talking about is for the free version too ;)

**Comment by stranoweb** [comment]
We have just released the new version 1.3.0 that fixes that issue. 
Please update the plugin, go to the plguin admin settings -> permalinks tab.
There’s a new option “custom pages” select it and save, you will have 5 new pages with the forms shortcodes inside.
