### ISSUE TITLE
Facebook login is alwayes in Italy 

### ISSUE THREAD

**Issue by frkhan** [stranoweb/stranoweb-ajax-login#7]
I found a bug if your premium plugin:
Location : wp-content\plugins\sw-ajax-login\assets\js\ajax-auth-script.js
Line number: 36
Existing code: $.getScript('https://connect.facebook.net/it_IT/sdk.js', function(){
Issue: it_IT is fixed here for all locale. My English customers see Italian  language while trying to do facebook login.

**Comment by stranoweb** [comment]
Hi Frkhan,

Thanks for reporting the issue, we will fix it asap.

Best

**Comment by stranoweb** [comment]
We have just released a new update that fixes this issue.
Thanks for reporting.

**Comment by frkhan** [comment]
Thanks

Kind Regards





Fazlur R Khan

Samadhan Consultants

34 Cleland Street

Mascot, NSW 2020

E : fazlu@samadhan.com.au <:%20fazlu@samadhan.com.au>

M : 0413 530 598

W : www.samadhan.com.au



Samadhan

C  O  N  S  U  L  T  A  N  T  S
