### ISSUE TITLE
Linkedin login stopped working (This resource is no longer available under v1 APIs)

### ISSUE THREAD

**Issue by gorfreed** [stranoweb/stranoweb-ajax-login#8]
Hello,
Unfortunately, the Linkedin login with your plugin has stopped working (it has without any problems for months). I had to switch to another Social Login plugin (One4all) where the login still works without problems.
Could you please look into this?
After entering Linkedin user credentials the redirect results in the following error:

Request Error: This resource is no longer available under v1 APIs. Raw Response: Array ( [errorCode] => 0 [message] => This resource is no longer available under v1 APIs [requestId] => CU7JZII8PY [status] => 410 [timestamp] => 1574109549239 )

The Address field shows the following URL (I replaced the code with XXX):
https://glqam.com/?code=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=XXXXXX

Thanks!

**Comment by stranoweb** [comment]
Thanks for letting me know, we will update the API call to the new version.

**Comment by stranoweb** [comment]
We have fixed the issue, the new version is now available on our website
